### ISSUE TITLE
Automatically detect and install required contexts (e.g. R, Py, SQL) using dar reproducible elements

### ISSUE THREAD

**Issue by nuest** [minrk/jupyter-dar#3]
Dar reproducible elements, https://github.com/substance/dar/blob/master/DarArticle.md#reproducible-elements, include the used language. Make sure the required language is available in the binder.

Currently, there are error messages for unsupported contexts:

![image](https://user-images.githubusercontent.com/1325054/39881447-4adb574a-5481-11e8-9009-bb9cccfac88b.png)

**Comment by nokome** [comment]
Hey @nuest! I only just saw this - was trying to get #5 done before you wake up for the morning (it's supposed to be a *global* sprint right :man_shrugging:): it adds support for Jupyter Python kernels as execution contexts as well as SQL.

But I really like the idea of scanning the files in the repo (DAR, or RMarkdown, or whatever) to determine what execution contexts should be installed in the Docker image.

**Comment by benmarwick** [comment]
Wow, this looks fantastic, great work! Really looking forward to seeing RMarkdown and R in a stencila document in binder!

**Comment by nuest** [comment]
@nokome just to be sure we're not missing anything: there is no server-side function yet for "give me all the languages of a document" - right?

My first guess is this is also related to #6, because the automatic detection has to be done in repo2docker and we need some functionality there to understand what is in the repo so we can adjust the install commands. And repo2docker will not (@minrk ?) include stencila, so we'll probably implement our own quick parser.

**Comment by nokome** [comment]
> here is no server-side function yet for "give me all the languages of a document" - right?

Correct.

> And repo2docker will not (@minrk ?) include stencila, so we'll probably implement our own quick parser.

Yep, you should be able to do this in a few lines by parsing the XML using XPath.

**Comment by nuest** [comment]
@minrk Do you want to move this issue to repo2docker?

**Comment by nuest** [comment]
@minrk With https://github.com/jupyter/repo2docker/pull/309 - will repo2docker just always install Python and R? Or is this issue still open? Can't really tell from the PR how repo2docker might magically handle different languages.

**Comment by nuest** [comment]
@minrk I want to wrap things up now and write the post - afaict the only requirement for the repo is that a `manifest.xml` is present, and then it will install `nbstencilaproxy`. _How are the programming languages detected? Is the presence of an `.Rmd` or `.ipynb` file picked up somewhere else?

**Comment by minrk** [comment]
@nuest that's right! Languages are detected in the same way as everything else on repo2docker, i.e. the presence of a `requirements.txt` or `environment.yml` or `install.R`.

**Comment by nuest** [comment]
I suggest to leave this open, and clarified the issue title a bit. A user might just use standard R stuff and not need an `install.R` script.

Also, the examples in https://github.com/jupyter/repo2docker/tree/master/tests/stencila/basic/archive don't include any of those files :thinking: I might still be missing something.

**Comment by nuest** [comment]
I suggest to leave this open, and clarified the issue title a bit. A user might just use standard R stuff and not need an `install.R` script, but right now it is needed to install Stencila, see https://github.com/nuest/stencila-r/commit/d8367eff5475a9b3074360c8d948dd161add25c5

**Comment by nuest** [comment]
Closed by https://github.com/jupyter/repo2docker/pull/457
