### ISSUE TITLE
Set up context for plain Python (not using JupyterPy)

### ISSUE THREAD

**Issue by nuest** [minrk/jupyter-dar#4]
Prerequisite for #3

**Comment by nokome** [comment]
PR #5 adds Stencila execution contexts for Node.js and SQLite (which have dependency analysis,  local execution, passing data between languages etc) and for the JupyterContext which acts as a bridge to Jupyter kernels (without those things).

Unfortunately the R and Python execution contexts require upgrades. I was in the middle of doing the R one - but then got distracted by this awesome little project :) - see https://github.com/stencila/r/issues/19#issuecomment-388189513

**Comment by nuest** [comment]
R is working now, so let's keep this one open for Python (i.e. the non Jupyter Kernel Python): https://github.com/stencila/py

Started working on this in https://github.com/nuest/nbstencilaproxy/tree/pycontext

**Comment by nuest** [comment]
Currently there is an error when creating the new Python context, it cannot spawn:

```bash
$ curl -X POST http://0.0.0.0:57659/stencila-host/PythonContext?token=82a0f12a61bb61ef4d2a67f5ba89429f42647ef8515d6cd0
Internal error: Error: Could not spawn peer using "/srv/conda/bin/python -m stencila spawn": Command failed: /srv/conda/bin/python -m stencila spawn
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/srv/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/conda/lib/python3.6/site-packages/stencila/__main__.py", line 35, in <module>
    result = func(**options)
  File "/srv/conda/lib/python3.6/site-packages/stencila/__init__.py", line 42, in spawn
    host.spawn(*args, **kwargs)
AttributeError: 'Host' object has no attribute 'spawn'


    at child.catch.error (/home/daniel/node_modules/stencila-node/lib/host/Host.js:738:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Looking in the container, the registration file is there and has matching python path.

```bash
daniel@gin-nuest:~/git/elife-sprint/jupyter-dar$ docker exec -it 9417f4a3cc77ae0da0b96260ee3a2d68ffbdb5fd0cd8807acb8eda8adfd9995f /bin/bash
daniel@9417f4a3cc77:~$ ls
app.js              nbstencilaproxy           README.md
archive             nbstencilaproxy.egg-info  setup.py
binder              new-session-button.png    stencila-host.js
CODE_OF_CONDUCT.md  node_modules              stencila-host.R
index.html          package.json              stencila.js
LICENSE             package-lock.json
daniel@9417f4a3cc77:~$ ls .stencila/hosts/
py.json  r.json
daniel@9417f4a3cc77:~$ cat .stencila/hosts/py.json
{
 "stencila": {
  "package": "py",
  "version": "0.28.0"
 },
 "spawn": [
  "/srv/conda/bin/python",
  "-m",
  "stencila",
  "spawn"
 ],
 "types": {
  "PythonContext": {
   "name": "PythonContext",
   "client": "ContextHttpClient"
  },
  "SqliteContext": {
   "name": "SqliteContext",
   "client": "ContextHttpClient"
  }
 }
```

The Python path seems to be fine, manually importing the module and running spawn gives the same error (sorry, not Python expert):

```bash
# (in the container)

daniel@9417f4a3cc77:~$ /srv/conda/bin/python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import stencila
>>> stencila.host.spawn()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Host' object has no attribute 'spawn'
>>> stencila.Host.spawn()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Host' has no attribute 'spawn'
>>> from stencila.host import Host, host
>>> host.spawn()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Host' object has no attribute 'spawn'
```

**As far as I can tell, the function `spawn()` is actually missing from `host`**: https://github.com/stencila/py/blob/master/stencila/host.py

@nokome Can you help?

**Comment by nokome** [comment]
Hi @nuest, yes the Python package is in upgrade limbo too. I'll work on it now so you at least have it running.

**Comment by nokome** [comment]
I've worked on the `stencila/py` package today. The last commit in the https://github.com/stencila/py/pull/16/ branch works for me locally with the `stencila/node` host as "primary" host that the UI connects to:

![image](https://user-images.githubusercontent.com/1152336/40532161-aa85bbfe-6052-11e8-9e2b-0dcee0755c7b.png)

I have tried to install it in the Binder image by adding a line to `requirements.txt`:
```
nbserverproxy
numpy
matplotlib
git://github.com/stencila/py.git@a760463020c08c9e3802d21215df8d2c2568c5e7#egg=stencila
```

But it seems like neither the Python or the R hosts are being registered because they are not picked up there:

![image](https://user-images.githubusercontent.com/1152336/40530865-7c53d526-604e-11e8-8599-0a247abd1b5b.png)

Does `postBuild` need `python -m stencila register` and `Rscript -e "stencila::register()"` added to it?

**Comment by nuest** [comment]
The `postBuild` should have the `python ... register`. See my branch [`pycontext`](https://github.com/nuest/nbstencilaproxy/tree/pycontext). The `Rscript ... register()` is in the file `binder/install.R`.

I got things working with the commit you referenced! :tada: 

![image](https://user-images.githubusercontent.com/1325054/40541683-19e27eb4-601d-11e8-8c26-3cfe9173ace8.png)

@nokome Do you plan to make a release or should we leave the commit ID for now?

@minrk Any difference in installing the `PythonContext` in `environment.yml` vs. `requirements.txt` ?

**Comment by nokome** [comment]
Well done!

Currently, all the Stencila code you are using is pinned to a commit or a
preview release 🙄. It's been a bit of a scramble to quickly update the
external execution hosts ie `node`, `r`, `py` so they can talk to the UI
and each other (with improvements in API and security). But they are
getting to a point now where they can be tagged and released. Just need a
few more fixes and test coverage before doing that. So, stick with the
commits for now, but I'll send a PR when releases are available.

BTW, that missing `get_ipython()` is expected right? Because you're not in
a `JupyterContext`.

**Comment by nuest** [comment]
Alright, so I'll prepare a PR to master branch with that pinned commit, and we can update the repo to a release when it's done.

And yes, that was the only way I could think of to demonstrate that a cell is not in the Jupyter context. _Any other ideas?_

**Comment by nokome** [comment]
> And yes, that was the only way I could think of to demonstrate that a cell is not in the Jupyter context. Any other ideas?

No, but one suggestion for this type of example is to change the comment line to something like " # Because this isn't a Jupyter kernel, the `get_ipython` function is not available and this cell returns an error" so that it makes it clearer that the error is expected.

**Comment by nuest** [comment]
@nokome Some work has happened since https://github.com/stencila/py/commit/a760463020c08c9e3802d21215df8d2c2568c5e7 - should I update the used version for `nbstencilaproxy` ?

**Comment by nokome** [comment]
@nuest Yes that would be good - please let me know if anything is broken! Also, the `stencila/r` package is updates (with better dependency analysis of cell code; needs the `graph` package from Bioconductor to be installed, see the README)
