### ISSUE TITLE
[Suggestion] Change urlpath to just "stencila"

### ISSUE THREAD

**Issue by RaoOfPhysics** [minrk/jupyter-dar#7]
At the moment, the `launch binder` URL points to `/stencila/` (which looks like `%2Fstencila%2F` in the URL bar).

For consistency (e.g. `rstudio`), I would suggest using just `stencila` without the leading and trailing slashes.

Probably related to https://github.com/minrk/jupyter-dar/issues/1.

**Comment by nuest** [comment]
I am not sure I get this one.

@minrk Can you confirm this?

**Comment by RaoOfPhysics** [comment]
Sorry for not being super clear, @nuest. I created the issue in a hurry.

For launching RStudio in Binder, the `urlpath` at the end of the URL has no leading or trailing slashes: `https://mybinder.org/v2/gh/binder-examples/r/master?urlpath=rstudio`

The current option for Stenila has slashes: `http://binder.minrk.net/v2/gh/minrk/jupyter-dar/master?urlpath=/stencila/`

It looks like this in the URL bar of your browser: `http://binder.minrk.net/v2/gh/minrk/jupyter-dar/master?urlpath=%2Fstencila%2F`

Probably best to all all editors (RStudio, Stencila etc.) using the same format. Does this make sense?
