### ISSUE TITLE
RContext cannot be started

### ISSUE THREAD

**Issue by nuest** [minrk/jupyter-dar#9]
When manually POSTing (replace token!) to stencila-host for a new `RContext`, we get an error message:

```
 curl -X POST http://localhost:8888/stencila-host/RContext?token=4d7c2e8f0bc840019e1d3acfd268748398b6d8697366128f
Internal error: TypeError: Cannot read property 'servers' of undefined
    at Promise.resolve.then.then (/opt/stencila/node_modules/stencila-node/lib/host/Host.js:330:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

To replicate run

```
docker build --tag jupyter-dar-r .
docker run -p 8888:8888 jupyter-dar-r
```

using the branch `rcontext` of this repo and open Jupyter using the link in the console. Then start a new terminal for Jupyter and manually fix the manifest file created by `stencila/r` to use `spawn` instead of `run` property, resuting in

![image](https://user-images.githubusercontent.com/1325054/39922281-b12df2b2-551e-11e8-9b9a-612cda44fa46.png)

Then kill all processes of `node stencila-host.js` (there are several).

Running the span command manually does return a manifest that looks OK, but in `Host.js` that JSON does not seem to be parsed at all (`manifest.servers` gives `Cannot read property 'servers' of undefined`).

![image](https://user-images.githubusercontent.com/1325054/39923722-226d6844-5525-11e8-9096-2c88abd1442b.png)

**Comment by nuest** [comment]
@nokome Can you help figuring out what is going wrong here?

**Comment by nokome** [comment]
@nuest : I have partially upgraded the R packaged to the new 0.28 version of the API. There are obviously some bugs to resolve. I'll look into it now.

**Comment by nuest** [comment]
@nokome Is your message https://gitter.im/stencila/stencila?at=5af6a5ccb84be71db9fed8e0 potentially a solution to this error?

**Comment by nokome** [comment]
@nuest sorry, only just saw this. Yes, seems to fix that issue. diff attached.

There are still upgrades I need to do on the `RContext`  I am hoping to finish them tomorrow. So if you can wait, it might save hassles.

![image](https://user-images.githubusercontent.com/1152336/40162855-49e19326-5a09-11e8-981f-dd230de0777c.png)

Edit: Github doesn't support attaching a `.patch` file! Below:

```patch
diff --git a/app.js b/app.js
index 90007b4..47af922 100644
--- a/app.js
+++ b/app.js
@@ -7,7 +7,7 @@
   window.addEventListener('load', () => {
     substance.substanceGlobals.DEBUG_RENDERING = substance.platform.devtools;
     stencila.StencilaWebApp.mount({
-      archiveId: substance.getQueryStringParam('archive') || 'py-jupyter',
+      archiveId: substance.getQueryStringParam('archive') || 'r-markdown',
       storageType: substance.getQueryStringParam('storage') || 'fs',
       storageUrl: substance.getQueryStringParam('storageUrl') || './archives'
     }, window.document.body);
diff --git a/install.R b/install.R
index 3ec693d..26a9151 100644
--- a/install.R
+++ b/install.R
@@ -1,8 +1,5 @@
 library(devtools)
 options(unzip = "internal")
-# see https://github.com/stencila/r/blob/master/README.md
-#devtools::install_github("stencila/r")
-# https://github.com/stencila/r/issues/21
-devtools::install_github("nuest/r")
-stencila:::install()
-# install.packages("tidyverse")
+
+devtools::install_github("stencila/r", ref="master")
+stencila::register()
diff --git a/stencila.js b/stencila.js
index 9cb56b9..ad7b9e4 100644
--- a/stencila.js
+++ b/stencila.js
@@ -23,5 +23,5 @@ console.log("DAR public URL: %s", serverUrl);
 console.log("Serving stencila on :%s", port);
 
 server.use("/", express.static(staticDir));
-server.use(express.logger('dev'));
+//server.use(express.logger('dev'));
 server.listen(port);
```

**Comment by nuest** [comment]
Sure, we have no deadline. Let me know when you finished your updates and I'll try them out!

**Comment by nuest** [comment]
@nokome How is it going?

**Comment by nokome** [comment]
@nuest : I guess you shouldn't have told me you don't have a deadline :slightly_smiling_face: I must admit that took some pressure off me so I am taking the time to do the necessary upgrades properly (including long overdue formalisation and documentation of the API!). I'll think I can finish off tomorrow - I'll ping you an update either way tomorrow.

**Comment by nuest** [comment]
Thanks! Just for testing (and to reduce the pressue ;-) ) I could also use the dev version of `stencila/r`, right? Could you push what you have to a branch?
